/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author UJANG
 */
public class Pegawai_KasirView extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtamaPegKasir
     */
    public Pegawai_KasirView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txfnotransaksi_pegkasir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfrole_pegkasir = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txfnip_pegkasir = new javax.swing.JLabel();
        foto_pegkasir = new java.awt.Panel();
        Image = new javax.swing.JLabel();
        btnlogout_pegkasir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txijumlahbarang_pegkasir = new javax.swing.JTextField();
        txfnamabarang_pegkasir = new javax.swing.JTextField();
        btntambahbarang_pegkasir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pegkasir = new javax.swing.JTable();
        txftotalharga_pegkasir = new javax.swing.JTextField();
        ceklishutang_pegkasir = new javax.swing.JCheckBox();
        btnbatal_pegkasir = new javax.swing.JButton();
        btnbayar_pegkasir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tanggal_pegkasir = new com.toedter.calendar.JDateChooser();
        btnNamaPeg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nomor Transaksi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal");

        txfrole_pegkasir.setText("Pegawai Kasir");

        txfnip_pegkasir.setText("11-111111111");

        foto_pegkasir.setBackground(new java.awt.Color(204, 204, 204));
        foto_pegkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout foto_pegkasirLayout = new javax.swing.GroupLayout(foto_pegkasir);
        foto_pegkasir.setLayout(foto_pegkasirLayout);
        foto_pegkasirLayout.setHorizontalGroup(
            foto_pegkasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        foto_pegkasirLayout.setVerticalGroup(
            foto_pegkasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        btnlogout_pegkasir.setText("Logout");

        jLabel6.setText("Jumlah :");

        jLabel8.setText("Nama barang :");

        btntambahbarang_pegkasir.setText("+ Tambah Barang");

        tabel_pegkasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Jumlah", "Harga Satuan", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_pegkasir);

        txftotalharga_pegkasir.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txftotalharga_pegkasir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ceklishutang_pegkasir.setBackground(new java.awt.Color(255, 255, 255));
        ceklishutang_pegkasir.setText("Hutang");

        btnbatal_pegkasir.setText("X Batal");

        btnbayar_pegkasir.setText("Bayar");

        btnNamaPeg.setText("Sukirman");
        btnNamaPeg.setBorder(null);
        btnNamaPeg.setBorderPainted(false);
        btnNamaPeg.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txftotalharga_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ceklishutang_pegkasir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbatal_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbayar_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(txijumlahbarang_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txfnamabarang_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btntambahbarang_pegkasir)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txfnotransaksi_pegkasir)
                                            .addComponent(tanggal_pegkasir, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfrole_pegkasir, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnlogout_pegkasir, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnNamaPeg, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txfnip_pegkasir, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)))
                                .addComponent(foto_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addComponent(jSeparator3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txfnotransaksi_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggal_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(foto_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txfrole_pegkasir)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNamaPeg)
                        .addGap(2, 2, 2)
                        .addComponent(txfnip_pegkasir)
                        .addGap(18, 18, 18)
                        .addComponent(btnlogout_pegkasir)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txijumlahbarang_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfnamabarang_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btntambahbarang_pegkasir))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txftotalharga_pegkasir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ceklishutang_pegkasir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbatal_pegkasir)
                            .addComponent(btnbayar_pegkasir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     private void makeFrameFullSize(JFrame aFrame){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        aFrame.setSize(screenSize.width, screenSize.height);
    }
     
    public JTextField gettxfnotransaksi_pegkasir() {
        return txfnotransaksi_pegkasir;
    }
    
    public JDateChooser gettanggal_pegkasir(){
        return tanggal_pegkasir;
    }

    public JCheckBox getCeklishutang_pegkasir() {
        return ceklishutang_pegkasir;
    }

    public JTable getTabel_pegkasir() {
        return tabel_pegkasir;
    }

    public JButton getTxfnama_pegkasir() {
        return btnNamaPeg;
    }

    public JTextField getTxfnamabarang_pegkasir() {
        return txfnamabarang_pegkasir;
    }

    public JLabel getTxfnip_pegkasir() {
        return txfnip_pegkasir;
    }

    public JLabel getTxfrole_pegkasir() {
        return txfrole_pegkasir;
    }

    public JTextField getTxftotalharga_pegkasir() {
        return txftotalharga_pegkasir;
    }

    public JTextField getTxijumlahbarang_pegkasir() {
        return txijumlahbarang_pegkasir;
    }

    public JButton getBtnbatal_pegkasir() {
        return btnbatal_pegkasir;
    }

    public JButton getBtnbayar_pegkasir() {
        return btnbayar_pegkasir;
    }

    public JButton getBtnlogout_pegkasir() {
        return btnlogout_pegkasir;
    }

    public JButton getBtntambahbarang_pegkasir() {
        return btntambahbarang_pegkasir;
    }

    public Panel getFoto_pegkasir() {
        return foto_pegkasir;
    }

    public JDateChooser getTanggal_pegkasir() {
        return tanggal_pegkasir;
    }

    public JTextField getTxfnotransaksi_pegkasir() {
        return txfnotransaksi_pegkasir;
    }    

    public JLabel getImage() {
        return Image;
    }
    
    public void addActionListener(ActionListener e){
        btnbatal_pegkasir.addActionListener(e);
        btnbayar_pegkasir.addActionListener(e);   
        btnlogout_pegkasir.addActionListener(e);   
        btntambahbarang_pegkasir.addActionListener(e);   
        btnNamaPeg.addActionListener(e);
    }
    
    public void reset(){
        txfnamabarang_pegkasir.setText("");
        txftotalharga_pegkasir.setText("");
        txijumlahbarang_pegkasir.setText("");
        tanggal_pegkasir.setDate(null);
        
        //Refresh Table
        DefaultTableModel tabel = (DefaultTableModel) getTabel_pegkasir().getModel();
        tabel.setRowCount(0);
        tabel.setRowCount(10);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai_KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai_KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai_KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai_KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawai_KasirView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton btnNamaPeg;
    private javax.swing.JButton btnbatal_pegkasir;
    private javax.swing.JButton btnbayar_pegkasir;
    private javax.swing.JButton btnlogout_pegkasir;
    private javax.swing.JButton btntambahbarang_pegkasir;
    private javax.swing.JCheckBox ceklishutang_pegkasir;
    private java.awt.Panel foto_pegkasir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tabel_pegkasir;
    private com.toedter.calendar.JDateChooser tanggal_pegkasir;
    private javax.swing.JTextField txfnamabarang_pegkasir;
    private javax.swing.JLabel txfnip_pegkasir;
    private javax.swing.JTextField txfnotransaksi_pegkasir;
    private javax.swing.JLabel txfrole_pegkasir;
    private javax.swing.JTextField txftotalharga_pegkasir;
    private javax.swing.JTextField txijumlahbarang_pegkasir;
    // End of variables declaration//GEN-END:variables
}
